name: GraphQL Compatibility
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  gql-breaking-changes:
    name: GraphQL Compatibility
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: base
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v1
        id: yarn-cache-base
        with:
          path: base/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('base/yarn.lock') }}-${{ hashFiles('base/.yarnrc.yml') }}
      - run: yarn install --immutable && yarn dedupe --check
        working-directory: base
        if: steps.yarn-cache-base.outputs.cache-hit != 'true'
      - run: yarn start -- --gen-schema
        working-directory: base

      - uses: actions/checkout@v2
        with:
          path: head
      - uses: actions/cache@v1
        id: yarn-cache-head
        with:
          path: head/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('head/yarn.lock') }}-${{ hashFiles('head/.yarnrc.yml') }}
      - run: yarn install --immutable && yarn dedupe --check
        if: steps.yarn-cache-head.outputs.cache-hit != 'true'
        working-directory: head
      - run: yarn start -- --gen-schema
        working-directory: head

      - name: Schema Diff
        run: |
          yarn dlx -q graphql-schema-diff \
            --use-colors --fail-on-breaking-changes --sort-schema \
            ../base/schema.graphql ./schema.graphql
        working-directory: head
        continue-on-error: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'breaking change') }}
